version: '1.1.1'
services:
  23rp00391-php:
    build: .
    ports:
      - 8082:80
    volumes:
      - ./:/var/www/html
  23rp00391-mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=schooldb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 9000:80